### ISSUE TITLE
About us design update

### ISSUE THREAD

**Issue by JElgar** [now-u/now-u-campaigns#36] opened 2020-07-12 22:21 UTC
Update about us page to match new v3 designs

**Comment by stellenberger** [comment] 2020-07-30 19:19
![iPad – 1](https://user-images.githubusercontent.com/53180713/88964957-fc23e580-d2a1-11ea-90c9-fdd317628698.png)
![iPhone 5-SE – 1](https://user-images.githubusercontent.com/53180713/88964977-ffb76c80-d2a1-11ea-8539-e13bfe66250c.png)
![Web - about us – 1](https://user-images.githubusercontent.com/53180713/88964979-00500300-d2a2-11ea-9296-7bdc025f272f.png)
![Web - about us – 2](https://user-images.githubusercontent.com/53180713/88964982-01813000-d2a2-11ea-920b-e5f831ee670c.png)

**Comment by stellenberger** [comment] 2020-07-30 19:21
There are 4 screen sizes here, start with the web/normal browser before moving onto the smaller ones :-) 

oh and IMPORTANT: Dont worry about the Footer with the Links, as it has already been designed and coded in another PR that should be merged soon.

**Comment by tunangst** [comment] 2020-08-02 19:12
One more question, how are we handling the typefaces? Are the going to be global sass variables changed? I assume we are keeping a consistent style through the site.

**Comment by JElgar** [comment] 2020-08-02 19:34
Yeah great point, the way the sass is setup is using modules. So we have sass for route specific stuff in those models and then I think all the global stuff goes in here: https://www.github.com/now-u/now-u-campaigns/tree/dev/src%2FApp.scss

**Comment by tunangst** [comment] 2020-08-02 20:15
These pictures have a blocky serif typeface that I can not find in our app variables. I only see '$headerFont: Rockwell;'
for these V3 design updates, is this header typeface listed anywhere in the redesign files.

I just essentially need to know what to change my font-family to.

**Comment by tunangst** [comment] 2020-08-02 21:35
The background of this collage is more of a white color than the pinker color wanted. We will have to fix this in the collage unless we are comfortable having a whiteish box around the collage that doesn't blend into the background.
collage background = #fdfdfd;
suggested v3 background = #fff9f2;

**Comment by stellenberger** [comment] 2020-08-03 10:08
Good point. 
Regarding the typefaces, use the old typeface as we can have a look at it later and maybe change all the designs at the same time. As you said, it would be good to keep it consistent throughout the site, so I think we will just leave the typeface out for now. 

As for the collage backround - very good point! Ill bring this up with the design team and we will make a PNG image for the collage so it will work with any background color, and ill get this back to you. You can use the old collage for now, as a placeholder.

**Comment by tunangst** [comment] 2020-08-03 20:28
I will post my pull request in a minute, just a few notes beforehand.
The small and medium designs have different HTML in the "Our story" section. I did not change this in my code, I didn't know if it was intended.
Also, I did reword some sentences to make it sound better. Let me know If I should revert these to how the image has them.

**Closed** 2020-08-05 17:43 UTC
Labels: enhancement
